'''
Problem Statement #
You have to implement the is_formation_possible() function which will find whether a given word can be formed by combining two words from a dictionary. We assume that all words are in lower case.
Input #
A dictionary and a query word containing lowercase characters.
Output #
Returns True if the given word can be generated by combining two words from the dictionary.
'''
from Trie import Trie
from TrieNode import TrieNode
# Create Trie => trie = Trie()
# TrieNode => {children, is_end_word, char,
# mark_as_leaf(), unmark_as_leaf()}
# get_root => trie.get_root()
# Insert a Word => trie.insert(key)
# Search a Word => trie.search(key) return true or false
# Delete a Word => trie.delete(key)

def if_formation_possible_v2(t,word):
    # Going over the word, recursively

    #print(f"Called with {word}")

    if len(word) == 0:
        return(True)
    
    node = t.root

    idx = 0

    #print(node.children)

    while idx<len(word) and node.children[ ord(word[idx]) - ord("a") ] is not None:
        node = node.children[ord(word[idx]) - ord("a")]
        #print(f"-- {node.char} {node.is_end_word}")
        if node.is_end_word:
            subword = if_formation_possible_v2(t,word[idx+1:])
            if subword:
               return(True)
        idx+=1
    return(False)



def is_formation_possible(dictionary, word):

    t = Trie()
    for w in dictionary:
        #print(f"Inserting {w}")
        t.insert(w)

    #t.print_trie()

    return (if_formation_possible_v2(t,word.lower()))
    


if __name__ == '__main__':
    dictionary = ["the", "hello", "there", "answer", "any",
                     "by", "world", "their", "abc", "educative"]

    word = "helloworld"
    print(is_formation_possible(dictionary,word))

    word = "anybythere"
    print(is_formation_possible(dictionary,word))

    word = "anybyhell"
    print(is_formation_possible(dictionary,word))    

    word = "thethe"
    print(is_formation_possible(dictionary,word)) 

    word = "theeducativethere"
    print(is_formation_possible(dictionary,word))